visageSDK: com.visagetechnologies.visagetrackerdemo.StartupActivity Class Reference
com.visagetechnologies.visagetrackerdemo.StartupActivity Class Reference
Activity started when application is ran.
Inherits Activity.
Public Member Functions
void onCreate (Bundle savedInstanceState)
Implementation of onCreate method provided by Activity interface.
void StartImages ()
Method called when user interacts with Track from image button.
void StartCam (int type)
Method called when user interacts with Track from cam button.
void handlePermissions ()
Method that handles permissions.
void onRequestPermissionsResult (int requestCode, String permissions[], int[] grantResults)
Method invoked when the user responds to permission request.
void copyFile (String rootDir, String filename)
Utility method called to copy required file to trackerdata folder.
void copyAssets (String rootDir)
Utility method called to create required directories and initiate copy of all assets required for tracking.
Detailed Description
Activity started when application is ran.
Definition at line 25 of file StartupActivity.java.
Member Function Documentation
void com.visagetechnologies.visagetrackerdemo.StartupActivity.copyAssets (String rootDir) inline
Utility method called to create required directories and initiate copy of all assets required for tracking.
Parameters
rootDir absolute path to root directory used for storing assets required for tracking.
Definition at line 171 of file StartupActivity.java.
References com.visagetechnologies.visagetrackerdemo.StartupActivity.copyFile().
Referenced by com.visagetechnologies.visagetrackerdemo.StartupActivity.onCreate().
void com.visagetechnologies.visagetrackerdemo.StartupActivity.copyFile (String rootDir, String filename) inline
Utility method called to copy required file to trackerdata folder.
Parameters
rootDir absolute path to directory where files should be copied.
filename name of file that will be copied.
Definition at line 137 of file StartupActivity.java.
Referenced by com.visagetechnologies.visagetrackerdemo.StartupActivity.copyAssets().
void com.visagetechnologies.visagetrackerdemo.StartupActivity.onCreate (Bundle savedInstanceState) inline
Implementation of onCreate method provided by Activity interface.
Called when Activity is started for the first time.
Definition at line 36 of file StartupActivity.java.
References com.visagetechnologies.visagetrackerdemo.StartupActivity.copyAssets(), and com.visagetechnologies.visagetrackerdemo.StartupActivity.handlePermissions().
The documentation for this class was generated from the following file:
StartupActivity.java