visageSDK: com.visagetechnologies.visagetrackerdemo.TrackerActivity Class Reference
com.visagetechnologies.visagetrackerdemo.TrackerActivity Class Reference
Activity called to initiate and control tracking for either tracking from camera or image.
Inherits Activity.
Public Member Functions
void StartCam ()
Starts tracking from camera and initializes surface for displaying tracking results.
void StartImage (String path)
Called to initialize and start tracking for image.
native void TrackerInit (String configFilename)
Interface to native method called for initializing tracker.
native void TrackFromImage (int width, int height)
Interface to native method called to start tracking from image.
native void TrackFromCam ()
Prepare raw image interface to track from camera.
native void TrackerStop ()
Interface to native method used to stop tracking.
Static Public Member Functions
static native float GetFps ()
Interface to native method called to obtain frame rate information from tracker.
static native float GetDisplayFps ()
Interface to native method called to obtain rendering frame rate information.
static native String GetStatus ()
Interface to native method called to obtain status of tracking information from tracker.
static native int GetTrackTime ()
Interface to native method called to obtain pure tracking time.
static native void setParameters (int width, int height, int orientation, int flip)
Interface to native method called to set camera frame parameteres.
Detailed Description
Activity called to initiate and control tracking for either tracking from camera or image.
Definition at line 26 of file TrackerActivity.java.
Member Function Documentation
static native float com.visagetechnologies.visagetrackerdemo.TrackerActivity.GetDisplayFps () static
Interface to native method called to obtain rendering frame rate information.
Returns
rendering frame rate value
static native float com.visagetechnologies.visagetrackerdemo.TrackerActivity.GetFps () static
Interface to native method called to obtain frame rate information from tracker.
Returns
frame rate value
static native String com.visagetechnologies.visagetrackerdemo.TrackerActivity.GetStatus () static
Interface to native method called to obtain status of tracking information from tracker.
Returns
status of tracking information as text.
static native int com.visagetechnologies.visagetrackerdemo.TrackerActivity.GetTrackTime () static
Interface to native method called to obtain pure tracking time.
Returns
status of tracking information as text.
static native void com.visagetechnologies.visagetrackerdemo.TrackerActivity.setParameters (int width, int height, int orientation, int flip) static
Interface to native method called to set camera frame parameteres.
void com.visagetechnologies.visagetrackerdemo.TrackerActivity.StartImage (String path) inline
Called to initialize and start tracking for image.
Also initializes surface for displaying tracking results.
Parameters
path absolute path to image file used for tracking. Sent from ImagesActivity using Bundle class provided by Android.
Definition at line 259 of file TrackerActivity.java.
References com.visagetechnologies.visagetrackerdemo.ImageTrackerView.getBitmapHeight(), com.visagetechnologies.visagetrackerdemo.ImageTrackerView.getBitmapWidth(), com.visagetechnologies.visagetrackerdemo.TrackerView.setGLView(), com.visagetechnologies.visagetrackerdemo.ImageTrackerView.SetOptimalBitmapSize(), and com.visagetechnologies.visagetrackerdemo.TrackerActivity.TrackerInit().
native void com.visagetechnologies.visagetrackerdemo.TrackerActivity.TrackerInit (String configFilename)
Interface to native method called for initializing tracker.
Parameters
configFilename absolute path to tracker configuration file.
Referenced by com.visagetechnologies.visagetrackerdemo.TrackerActivity.StartCam(), and com.visagetechnologies.visagetrackerdemo.TrackerActivity.StartImage().
native void com.visagetechnologies.visagetrackerdemo.TrackerActivity.TrackFromImage (int width, int height)
Interface to native method called to start tracking from image.
Parameters
width width of image file used for tracking
height height of image used for tracking
The documentation for this class was generated from the following file:
TrackerActivity.java