visageSDK: com.visagetechnologies.visagetrackerdemo.ImageTrackerView Class Reference
com.visagetechnologies.visagetrackerdemo.ImageTrackerView Class Reference
Derives from TrackerView.
Public Member Functions
void surfaceCreated (SurfaceHolder holder)
Implementation of surfaceCreated method provided by SurfaceHolder.Callback class.
void surfaceChanged (SurfaceHolder holder, int format, int width, int height)
Implementation of surfaceChanged method provided by SurfaceHolder.Callback class.
void surfaceDestroyed (SurfaceHolder holder)
Implementation of surfaceDestroyed method provided by SurfaceHolder.Callback class.
int getBitmapWidth ()
Called to obtain width of bitmap used for tracking.
int getBitmapHeight ()
Called to obtain height of bitmap used for tracking.
void SetOptimalBitmapSize ()
Utility method used to resize bitmap of image used for tracking.
void LoadFromFile ()
Utility method called for loading the image from file into a Bitmap object.
byte[] ConvertToByte ()
Utility method called to obtain raw pixel data from bitmap object in which image used for tracking is loaded.
void run ()
Implementation of run method of Runnable interface.
Public Member Functions inherited from com.visagetechnologies.visagetrackerdemo.TrackerView
void setGLView (TrackerGLSurfaceView tview)
Called to set GLSurfaceView used for rendering with OpenGL.
Static Public Member Functions
static native void WriteFrameImage (byte[] frame, int width, int height)
Interface to native method used for passing raw pixel data to tracker.
Detailed Description
Derives from TrackerView.
Class ImageTrackerView is used for providing tracker with necessary image data and controlling surface used to display results while tracking from image file. Implements Runnable interface provided by Android. Runnable interface is used for implementation of simple multi-threading.
Definition at line 19 of file ImageTrackerView.java.
Member Function Documentation
byte [] com.visagetechnologies.visagetrackerdemo.ImageTrackerView.ConvertToByte () inline
Utility method called to obtain raw pixel data from bitmap object in which image used for tracking is loaded.
Pixel data is obtained as array of integers by calling getPixels method of Bitmap class. Each element of obtained array of integer represents one pixel of bitmap. In order to create pixel data usable by tracker it is necessary to extract red, green and blue color values from array of integers and store it as a byte array.
Returns
byte array of raw pixel data obtained from image used for tracking.
Definition at line 149 of file ImageTrackerView.java.
Referenced by com.visagetechnologies.visagetrackerdemo.ImageTrackerView.surfaceCreated().
int com.visagetechnologies.visagetrackerdemo.ImageTrackerView.getBitmapHeight () inline
Called to obtain height of bitmap used for tracking.
Returns
height of bitmap in pixels.
Definition at line 90 of file ImageTrackerView.java.
Referenced by com.visagetechnologies.visagetrackerdemo.TrackerActivity.StartImage().
int com.visagetechnologies.visagetrackerdemo.ImageTrackerView.getBitmapWidth () inline
Called to obtain width of bitmap used for tracking.
Returns
width of bitmap in pixels
Definition at line 81 of file ImageTrackerView.java.
Referenced by com.visagetechnologies.visagetrackerdemo.TrackerActivity.StartImage().
void com.visagetechnologies.visagetrackerdemo.ImageTrackerView.run () inline
Implementation of run method of Runnable interface.
Android requires that all rendering to a surface is done from separate thread than the one which created the View object. Rendering thread is started from surfaceCreated method. Method calls rendering loop of application.
Definition at line 181 of file ImageTrackerView.java.
void com.visagetechnologies.visagetrackerdemo.ImageTrackerView.SetOptimalBitmapSize () inline
Utility method used to resize bitmap of image used for tracking.
Images that are larger than the screen are resized to fit the screen while keeping the initial ratio between height and width. In order to interpret images in a correct way OpenCV requires image size to be divisible by 4. Images that have either width or height value that does not satisfy this condition are additionally resized until they do. This slightly changes ratio between width and height.
Definition at line 100 of file ImageTrackerView.java.
Referenced by com.visagetechnologies.visagetrackerdemo.TrackerActivity.StartImage().
void com.visagetechnologies.visagetrackerdemo.ImageTrackerView.surfaceChanged (SurfaceHolder holder, int format, int width, int height) inline
Implementation of surfaceChanged method provided by SurfaceHolder.Callback class.
Sets new width and height values of view.
Definition at line 61 of file ImageTrackerView.java.
void com.visagetechnologies.visagetrackerdemo.ImageTrackerView.surfaceCreated (SurfaceHolder holder) inline
Implementation of surfaceCreated method provided by SurfaceHolder.Callback class.
Creates and starts rendering thread. Calls WriteFrame method to pass image data to tracker.
Definition at line 51 of file ImageTrackerView.java.
References com.visagetechnologies.visagetrackerdemo.ImageTrackerView.ConvertToByte(), and com.visagetechnologies.visagetrackerdemo.ImageTrackerView.WriteFrameImage().
void com.visagetechnologies.visagetrackerdemo.ImageTrackerView.surfaceDestroyed (SurfaceHolder holder) inline
Implementation of surfaceDestroyed method provided by SurfaceHolder.Callback class.
Ends rendering loop. Calls TrackerStop method to stop tracking.
Definition at line 71 of file ImageTrackerView.java.
static native void com.visagetechnologies.visagetrackerdemo.ImageTrackerView.WriteFrameImage (byte[] frame, int width, int height) static
Interface to native method used for passing raw pixel data to tracker.
Called from surfaceCreated.
Parameters
frame raw pixel data of image used for tracking.
width width of image used for tracking.
height height of image used for tracking.
Referenced by com.visagetechnologies.visagetrackerdemo.ImageTrackerView.surfaceCreated().
The documentation for this class was generated from the following file:
ImageTrackerView.java