visageSDK: com.visagetechnologies.facedetectdemo.DetectorRenderer Class Reference
com.visagetechnologies.facedetectdemo.DetectorRenderer Class Reference
TrackerRenderer class provides implementation of rendering functions required for displaying detection results.
Inherits Renderer.
Public Member Functions
void onDrawFrame (GL10 gl)
Implementation of onDrawFrame method provided by GLSurfaceView.Renderer interface.
void onSurfaceChanged (GL10 gl, int width, int height)
Implementation of surfaceChanged method provided by SurfaceHolder.Callback class.
native void displayResults ()
Interface to native method used to draw detection results.
native void displayIdentity ()
Interface to native method used to draw recognition results.
native void drawFrame (int _width, int _height)
Interface to native method used to draw current frame analyzed by detector.
Detailed Description
TrackerRenderer class provides implementation of rendering functions required for displaying detection results.
Definition at line 20 of file DetectorRenderer.java.
Member Function Documentation
void com.visagetechnologies.facedetectdemo.DetectorRenderer.onDrawFrame (GL10 gl) inline
Implementation of onDrawFrame method provided by GLSurfaceView.Renderer interface.
Called to render every frame.
Parameters
gl OpenGL context.
Definition at line 43 of file DetectorRenderer.java.
References com.visagetechnologies.facedetectdemo.DetectorRenderer.displayIdentity(), com.visagetechnologies.facedetectdemo.DetectorRenderer.displayResults(), and com.visagetechnologies.facedetectdemo.DetectorRenderer.drawFrame().
void com.visagetechnologies.facedetectdemo.DetectorRenderer.onSurfaceChanged (GL10 gl, int width, int height) inline
Implementation of surfaceChanged method provided by SurfaceHolder.Callback class.
Sets new width and height values of view.
Definition at line 59 of file DetectorRenderer.java.
The documentation for this class was generated from the following file:
DetectorRenderer.java