visageSDK: com.visagetechnologies.facedetectdemo.ImagesActivity Class Reference
com.visagetechnologies.facedetectdemo.ImagesActivity Class Reference
Activity started when application is launched.
Inherits Activity.
Public Member Functions
void onCreate (Bundle savedInstanceState)
Implementation of onCreate method provided by Activity interface.
void handlePermissions ()
Method that handles permissions.
void onRequestPermissionsResult (int requestCode, String permissions[], int[] grantResults)
Method invoked when the user responds to permission request.
void copyFile (String rootDir, String filename)
Utility method called to copy required file to trackerdata folder.
void copyAssets (String rootDir)
Utility method called to create required directories and initiate copy of all assets required for tracking.
Protected Member Functions
void onActivityResult (int requestCode, int resultCode, Intent data)
Called when user selects image.
Detailed Description
Activity started when application is launched.
ImagesActivity images gallery on Android device. User can choose image that will be used for detection.
Definition at line 28 of file FaceDetectDemo/app/src/main/java/com/visagetechnologies/facedetectdemo/ImagesActivity.java.
Member Function Documentation
void com.visagetechnologies.facedetectdemo.ImagesActivity.copyAssets (String rootDir) inline
Utility method called to create required directories and initiate copy of all assets required for tracking.
Parameters
rootDir absolute path to root directory used for storing assets required for tracking.
Definition at line 225 of file FaceDetectDemo/app/src/main/java/com/visagetechnologies/facedetectdemo/ImagesActivity.java.
References com.visagetechnologies.facedetectdemo.ImagesActivity.copyFile().
Referenced by com.visagetechnologies.facedetectdemo.ImagesActivity.onCreate().
void com.visagetechnologies.facedetectdemo.ImagesActivity.copyFile (String rootDir, String filename) inline
Utility method called to copy required file to trackerdata folder.
Parameters
rootDir absolute path to directory where files should be copied.
filename name of file that will be copied.
Definition at line 188 of file FaceDetectDemo/app/src/main/java/com/visagetechnologies/facedetectdemo/ImagesActivity.java.
Referenced by com.visagetechnologies.facedetectdemo.ImagesActivity.copyAssets().
void com.visagetechnologies.facedetectdemo.ImagesActivity.onCreate (Bundle savedInstanceState) inline
Implementation of onCreate method provided by Activity interface.
Called when Activity is started for the first time.
Definition at line 45 of file FaceDetectDemo/app/src/main/java/com/visagetechnologies/facedetectdemo/ImagesActivity.java.
References com.visagetechnologies.facedetectdemo.ImagesActivity.copyAssets(), and com.visagetechnologies.facedetectdemo.ImagesActivity.handlePermissions().
The documentation for this class was generated from the following file:
FaceDetectDemo/app/src/main/java/com/visagetechnologies/facedetectdemo/ImagesActivity.java