visageSDK: com.visagetechnologies.facedetectdemo.DetectorActivity Class Reference
com.visagetechnologies.facedetectdemo.DetectorActivity Class Reference
Activity called to initiate and control detection.
Inherits Activity.
Public Member Functions
void StartDetector (String path)
Called to initialize and start detection.
native void DetectorInit (String appPath, String modelName, int chooseFeature)
Interface to native method used to initialize VisageFeaturesDetector object.
native void CleanUp ()
Interface to native method used to clean up resources.
Detailed Description
Activity called to initiate and control detection.
Definition at line 13 of file DetectorActivity.java.
Member Function Documentation
native void com.visagetechnologies.facedetectdemo.DetectorActivity.DetectorInit (String appPath, String modelName, int chooseFeature)
Interface to native method used to initialize VisageFeaturesDetector object.
Parameters
appPath path to root folder where Android application data is stored
modelName name of generic Active Appearance Model file used for detection
Referenced by com.visagetechnologies.facedetectdemo.DetectorActivity.StartDetector().
void com.visagetechnologies.facedetectdemo.DetectorActivity.StartDetector (String path) inline
Called to initialize and start detection.
Also initializes surface for displaying detection results.
Parameters
path absolute path to image file used for detecting. Sent from ImagesActivity using Bundle class provided by Android.
Definition at line 52 of file DetectorActivity.java.
References com.visagetechnologies.facedetectdemo.DetectorActivity.DetectorInit(), and com.visagetechnologies.facedetectdemo.DetectorView.setGLView().
The documentation for this class was generated from the following file:
DetectorActivity.java