visageSDK: VisageSDK::VisageFeaturesDetector Class Reference
VisageSDK::VisageFeaturesDetector Class Reference
Faces and facial features detector implementation.
#include <VisageFeaturesDetector.h>
Public Member Functions
VisageFeaturesDetector ()
Constructor.
~VisageFeaturesDetector ()
Destructor.
bool Initialize (const char *path)
Initialise the feature detector.
int detectFaces (VsImage *frame, VsRect *faces, int maxFaces=1, float minFaceScale=0.1f, float maxFaceScale=1.0f, bool useRefinementStep=true)
Performs face detection in a still image.
int detectFacialFeatures (VsImage *frame, FaceData *output, int maxFaces=1, float minFaceScale=0.1f, float maxFaceScale=1.0f, bool outputOnly2DFeatures=false)
Performs faces and facial features detection in a still image.
Detailed Description
Faces and facial features detector implementation.
This class can be used to detect one or more faces and their facial features in an image. The input is an image bitmap or an image file in one of the supported file formats: JPEG, PNG, BMP or PPM.
Function detectFaces() performs a fast face detection on the image. The result is, for each detected face, a VsRect object containing facial bounding box.
Function detectFacialFeatures() performs a face and facial features detection on the image. The results is, for each detected face, FaceData object containing 3D head pose, coordinates of facial feature points (e.g. pupils, nose tip, lip corners etc.), 3D face model fitted to the face and more. Please refer to the FaceData documentation for detailed description of returned data.
To use the detector, it must first be initialized by calling the function Initialize().
Implemented in libVisageVision.lib
Demonstrated in FaceDetector sample project.
Definition at line 68 of file VisageFeaturesDetector.h.
Member Function Documentation
int VisageSDK::VisageFeaturesDetector::detectFaces (VsImage * frame, VsRect * faces, int maxFaces = 1, float minFaceScale = 0.1f, float maxFaceScale = 1.0f, bool useRefinementStep = true)
Performs face detection in a still image.
The algorithm detects one or more faces. For each detected face a square facial bounding box is returned.
The results are returned in form of VsRect objects. An array of VsRect objects passed to this method as output parameter should be allocated to maxFaces size. For example:
VsRect* faces = new VsRect[maxFaces];
n = this->m_Detector->detectFaces(image, faces, maxFaces);
After this call, n contains the number of detected faces. The first n members of the faces array are filled with resulting bounding boxes for each detected face. If maxFaces is smaller than the number of faces actually detected in the image, the function will return only first maxFaces detected faces.
VsImage is the image storage class similar to IplImage from OpenCV, it has the same structure and members so it can be used like IplImage. Please refer to OpenCV documentation for details of accessing IplImage data members; the basic members are the size of the image (frame->width, frame->height) and the pointer to the actual pixel data of the image (frame->imageData).
Following image formats are supported:
VISAGE_FRAMEGRABBER_FMT_RGB: each pixel of the image is represented by three bytes representing red, green and blue channels, respectively.
VISAGE_FRAMEGRABBER_FMT_RGBA: each pixel of the image is represented by four bytes representing red, green, blue and alpha (ignored) channels, respectively.
VISAGE_FRAMEGRABBER_FMT_LUMINANCE: each pixel of the image is represented by one byte representing the luminance (gray level) of the image. Origin must be:
VISAGE_FRAMEGRABBER_ORIGIN_TL: Origin is the top left pixel of the image. Pixels are ordered row-by-row starting from top left.
Note that the input image is internally converted to grayscale.
Parameters
frame the input image.
faces pointer to an array of VsRect objects in which the results will be returned.
maxFaces maximum number of faces to be detected
minFaceScale scale of smallest face to be searched for, defined as decimal fraction [0.0 - 1.0] of input image size (min(width, height))
maxFaceScale scale of largest face to be searched for, defined as decimal fraction [0.0 - 1.0] of input image size (min(width, height))
useRefinementStep if set to true, additional refinement algorithm will be used resulting with more precise facial bounding boxes and lower FPR, but higher detection time
Returns
number of detected faces (0 or more)
int VisageSDK::VisageFeaturesDetector::detectFacialFeatures (VsImage * frame, FaceData * output, int maxFaces = 1, float minFaceScale = 0.1f, float maxFaceScale = 1.0f, bool outputOnly2DFeatures = false)
Performs faces and facial features detection in a still image.
The algorithm detects one or more faces and their features. The results are, for each detected face, the 3D head pose, gaze direction, eye closure, the coordinates of facial feature points (e.g. chin tip, nose tip, lip corners etc.) and 3D face model fitted to the face. If outputOnly2DFeatures is set, only the 2D feature points will be returned.
The results are returned in form of FaceData objects. An array of FaceData objects passed to this method as output parameter should be allocated to maxFaces size. For example:
FaceData* data = new FaceData[maxFaces];
n = this->m_Detector->detectFacialFeatures(image, data, maxFaces, minFaceScale);
After this call, n contains the number of faces actually detected. The first n members of the data array are filled with resulting data for each detected face. Please refer to the FaceData documentation for detailed description of returned parameters. If maxFaces is smaller than the number of faces actually present in the image, the function will return only first maxFaces detected faces.
VsImage is the image storage class similar to IplImage from OpenCV, it has the same structure and members so it can be used like IplImage. Please refer to OpenCV documentation for details of accessing IplImage data members; the basic members are the size of the image (frame->width, frame->height) and the pointer to the actual pixel data of the image (frame->imageData).
Following image formats are supported:
VISAGE_FRAMEGRABBER_FMT_RGB: each pixel of the image is represented by three bytes representing red, green and blue channels, respectively.
VISAGE_FRAMEGRABBER_FMT_RGBA: each pixel of the image is represented by four bytes representing red, green, blue and alpha (ignored) channels, respectively.
VISAGE_FRAMEGRABBER_FMT_LUMINANCE: each pixel of the image is represented by one byte representing the luminance (gray level) of the image. Origin must be:
VISAGE_FRAMEGRABBER_ORIGIN_TL: Origin is the top left pixel of the image. Pixels are ordered row-by-row starting from top left.
Note that the input image is internally converted to grayscale.
Parameters
frame the input image.
output pointer to an array of FaceData objects in which the results will be returned.
maxFaces maximum number of faces to be detected
minFaceScale scale of smallest face to be searched for, defined as decimal fraction [0.0 - 1.0] of input image size (min(width, height))
maxFaceScale scale of largest face to be searched for, defined as decimal fraction [0.0 - 1.0] of input image size (min(width, height))
outputOnly2DFeatures if set, detection time will be reduced and only FeaturePoints2D will be returned
Returns
number of detected faces (0 or more)
See also
FaceData
Referenced by createGallery(), Java_com_visagetechnologies_facedetectdemo_ImageDetectorView_DetectFeatures(), and Java_com_visagetechnologies_facedetectdemo_ImageDetectorView_recognizeFace().
bool VisageSDK::VisageFeaturesDetector::Initialize (const char * path)
Initialise the feature detector.
Several data files are needed for facial features detection and the path to the data folder containing these data files must be passed to the initialization function, for example:
std::string dataPath("."); //Assuming the current working folder contains data files(from "bdtsdata" folder).
m_Detector->Initialize(dataPath.c_str());
The data folder must contain:
a subfolder "bdtsdata" with complete contents as provided in visage|SDK;
files candide3.fdp, candide3.wfm, jk_300.fdp, jk_300.wfm and FaceDetector.cfg.
In visage|SDK, the data folder with necessary files is Samples/data. These files must be distributed with any application using VisageFeaturesDetector.
Parameters
path the path to the detector data files
Returns
true if successful
Referenced by Java_com_visagetechnologies_facedetectdemo_DetectorActivity_DetectorInit(), and Java_com_visagetechnologies_facedetectdemo_RecognitionActivity_initRecognition().
The documentation for this class was generated from the following file:
VisageFeaturesDetector.h