visageSDK: DrawingWrapper.cpp File Reference
DrawingWrapper.cpp File Reference
Uses OpenGL to display image processed by VisageFaceRecognition or VisageFeaturesDetector functionality.
#include <jni.h>
#include <EGL/egl.h>
#include <GLES/gl.h>
#include <vector>
#include <stdio.h>
#include "VisageDrawing.h"
#include "VisageFeaturesDetector.h"
#include "Common.h"
#include "WrapperOpenCV.h"
#include "cv.h"
#include "VisageFaceRecognition.h"
#include <android/log.h>
Functions
void initFrameTexture (IplImage *image)
Method for initializing video texture through OpenGL.
void setFrameTexture (IplImage *image)
Method for refreshing video texture through OpenGL.
void DrawImage ()
Method for displaying video through OpenGL.
void Java_com_visagetechnologies_facedetectdemo_DetectorRenderer_drawFrame (JNIEnv *env, jobject obj, jint width, jint height)
Method for displaying image used for detection/recognition through OpenGL ES.
Variables
GLuint frameTexId = 0
Texture ID for displaying frames.
IplImage * _drawImage = 0
Image to be drawn.
float xTexCoord
Texture coordinates for displaying frames.
float yTexCoord
Texture coordinates for displaying frames.
int xTexSize
Size of the texture for displaying frames.
int yTexSize
Size of the texture for displaying frames.
float videoAspect
Aspect of the video.
int glWidth
Size of the OpenGL view.
int glHeight
Size of the OpenGL view.
Detailed Description
Uses OpenGL to display image processed by VisageFaceRecognition or VisageFeaturesDetector functionality.
Key members of wrapper are:
visageFaceRecogntion: the VisageFaceRecogntion object
displayIdentity: method that demonstrates how to display data obtained from VisageFaceRecognition
Definition in file DrawingWrapper.cpp.
Function Documentation
void initFrameTexture (IplImage * image)
Method for initializing video texture through OpenGL.
The texture must have dimensions that are power of 2, so video data will cover only part of the texture.
Parameters
image frame to initialize video display with
Definition at line 88 of file DrawingWrapper.cpp.
References glHeight, glWidth, and videoAspect.
Referenced by Java_com_visagetechnologies_facedetectdemo_DetectorRenderer_drawFrame().
void Java_com_visagetechnologies_facedetectdemo_DetectorRenderer_drawFrame (JNIEnv * env, jobject obj, jint width, jint height)
Method for displaying image used for detection/recognition through OpenGL ES.
This method is called by the application rendering thread to display detection/recognition results.
Parameters
width width of GLSurfaceView used for rendering.
height height of GLSurfaceView used for rendering.
Definition at line 351 of file DrawingWrapper.cpp.
References DrawImage(), initFrameTexture(), and setFrameTexture().
void setFrameTexture (IplImage * image)
Method for refreshing video texture through OpenGL.
The part of the texture containing video data is refreshed with current frame data.
Parameters
image frame to refresh video display with
Definition at line 150 of file DrawingWrapper.cpp.
Referenced by Java_com_visagetechnologies_facedetectdemo_DetectorRenderer_drawFrame().
Variable Documentation
GLuint frameTexId = 0
Texture ID for displaying frames.
Texture ID for displaying frames.
Definition at line 37 of file DrawingWrapper.cpp.