visageSDK: VisageFaceRecognitionWrapper.cpp File Reference
VisageFaceRecognitionWrapper.cpp File Reference
Implementation of simple interface around visage|SDK VisageFaceRecogntion functionality.
#include <jni.h>
#include <EGL/egl.h>
#include <GLES/gl.h>
#include <vector>
#include <stdio.h>
#include "VisageDrawing.h"
#include "VisageFeaturesDetector.h"
#include "Common.h"
#include "WrapperOpenCV.h"
#include "cv.h"
#include "highgui.h"
#include "VisageFaceRecognition.h"
#include <android/log.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
Functions
int createGallery ()
Method which adds descriptors to VisageFaceRecognition gallery.
void Java_com_visagetechnologies_facedetectdemo_RecognitionActivity_load (JNIEnv *env, jobject obj, jobject assetManager)
Method that loads AAssetManager.
void Java_com_visagetechnologies_facedetectdemo_RecognitionActivity_initRecognition (JNIEnv *env, jobject obj, jstring appPath)
Method for initializing the recognizer.
void Java_com_visagetechnologies_facedetectdemo_ImageDetectorView_recognizeFace (JNIEnv *env, jobject obj, jbyteArray frame, jint width, jint height)
Method which performs face recognition on a given image.
void Java_com_visagetechnologies_facedetectdemo_DetectorRenderer_displayIdentity (JNIEnv *env, jobject obj)
Method for displaying recognition results.
void Java_com_visagetechnologies_facedetectdemo_RecognitionActivity_CleanUp (JNIEnv *env, jobject obj)
Method for cleaning up resources used by application.
Variables
GLuint frameTexId
Texture ID for displaying frames.
IplImage * _drawImage
Image to be drawn.
Detailed Description
Implementation of simple interface around visage|SDK VisageFaceRecogntion functionality.
In order for Android application, which uses Java as its primary programming language, to communicate with visage|SDK functionality, which uses C++ as its primary language it is necessary to use Java Native Interface as a framework between the two.
Key members of wrapper are:
VisageFaceRecogntion: the VisageFaceRecogntion object
displayIdentity: method that demonstrates how to display data obtained from VisageFaceRecognition
Definition in file VisageFaceRecognitionWrapper.cpp.
Function Documentation
int createGallery ()
Method which adds descriptors to VisageFaceRecognition gallery.
This method goes through all pre-loaded images in the Famous Actors/gallery/ folder and adds corresponding descriptor to VisageFaceRecognition gallery for each. Returns 0 if VisageFeaturesDetector object has not been initialized yet or if the Famous Actors/gallery/ folder is empty.
Definition at line 101 of file VisageFaceRecognitionWrapper.cpp.
References VisageSDK::VisageFaceRecognition::addDescriptor(), and VisageSDK::VisageFeaturesDetector::detectFacialFeatures().
Referenced by Java_com_visagetechnologies_facedetectdemo_RecognitionActivity_initRecognition().
void Java_com_visagetechnologies_facedetectdemo_ImageDetectorView_recognizeFace (JNIEnv * env, jobject obj, jbyteArray frame, jint width, jint height)
Method which performs face recognition on a given image.
Performs face recognition on a given image and returns the image with the name of the recognized person or the person with the most similar face found in the VisageFaceRecognition gallery.
Definition at line 195 of file VisageFaceRecognitionWrapper.cpp.
References VisageSDK::VisageFeaturesDetector::detectFacialFeatures(), VisageSDK::VisageFaceRecognition::extractDescriptor(), VisageSDK::VisageFaceRecognition::getDescriptorSize(), VisageSDK::VisageFaceRecognition::is_initialized, and VisageSDK::VisageFaceRecognition::recognize().
void Java_com_visagetechnologies_facedetectdemo_RecognitionActivity_initRecognition (JNIEnv * env, jobject obj, jstring appPath)
Method for initializing the recognizer.
This method creates a new VisageFaceRecognition object and calls method createGallery() for loading VisageFaceRecognition gallery.
Definition at line 150 of file VisageFaceRecognitionWrapper.cpp.
References createGallery(), VisageSDK::VisageFeaturesDetector::Initialize(), and VisageSDK::VisageFaceRecognition::is_initialized.
Variable Documentation
GLuint frameTexId
Texture ID for displaying frames.
Texture ID for displaying frames.
Definition at line 74 of file AndroidWrapper.cpp.