visageSDK: VisageFeaturesDetectorWrapper.cpp File Reference
VisageFeaturesDetectorWrapper.cpp File Reference
Implementation of simple interface around visage|SDK VisageFeaturesDetector functionality.
#include <jni.h>
#include <EGL/egl.h>
#include <GLES/gl.h>
#include <vector>
#include <stdio.h>
#include "VisageDrawing.h"
#include "VisageFeaturesDetector.h"
#include "Common.h"
#include "highgui.h"
#include "VisageFaceRecognition.h"
#include "VisageFaceAnalyser.h"
#include <android/log.h>
Functions
void Java_com_visagetechnologies_facedetectdemo_DetectorActivity_DetectorInit (JNIEnv *env, jobject obj, jstring appPath, jstring modelName, jint chooseFeature)
Method for initializing the detector.
void Java_com_visagetechnologies_facedetectdemo_ImageDetectorView_DetectFeatures (JNIEnv *env, jobject obj, jbyteArray frame, jint width, jint height)
Method for passing raw image data to detector and initiating detection of features in it.
void Java_com_visagetechnologies_facedetectdemo_DetectorRenderer_displayResults (JNIEnv *env, jobject obj)
Method for displaying detection results.
void Java_com_visagetechnologies_facedetectdemo_DetectorActivity_CleanUp (JNIEnv *env, jobject obj)
Method for cleaning up resources used by application.
Variables
GLuint frameTexId
Texture ID for displaying frames.
IplImage * _drawImage
Image to be drawn.
Detailed Description
Implementation of simple interface around visage|SDK VisageFeaturesDetector functionality.
In order for Android application, which uses Java as its primary programming language, to communicate with visage|SDK functionality, which uses C++ as its primary language it is necessary to use Java Native Interface as a framework between the two.
Key members of wrapper are:
visageFeaturesDetector: the VisageFeaturesDetector object
displayResults: method that demonstrates how to display data obtained from VisageFeaturesDetector
Definition in file VisageFeaturesDetectorWrapper.cpp.
Function Documentation
void Java_com_visagetechnologies_facedetectdemo_DetectorActivity_DetectorInit (JNIEnv * env, jobject obj, jstring appPath, jstring modelName, jint chooseFeature)
Method for initializing the detector.
This method creates a new VisageFeaturesDetector object and initializes it.
Parameters
appPath path to root folder where Android application data is stored
modelName name of generic Active Appearance Model file used for detection
Definition at line 88 of file VisageFeaturesDetectorWrapper.cpp.
References VisageSDK::VisageFaceAnalyser::init(), and VisageSDK::VisageFeaturesDetector::Initialize().
void Java_com_visagetechnologies_facedetectdemo_ImageDetectorView_DetectFeatures (JNIEnv * env, jobject obj, jbyteArray frame, jint width, jint height)
Method for passing raw image data to detector and initiating detection of features in it.
Detection results are returned through FDP object. By calling static method DrawFDP of Common class detection results are drawn directly on top of image used for detection.
Parameters
frame raw image data of image used for detection.
width width of image used for detection.
height height of image used for detection.
Definition at line 133 of file VisageFeaturesDetectorWrapper.cpp.
References VisageSDK::VisageFeaturesDetector::detectFacialFeatures().
Variable Documentation
GLuint frameTexId
Texture ID for displaying frames.
Texture ID for displaying frames.
Definition at line 74 of file AndroidWrapper.cpp.